name: Push Artifacts
description: "Push Artifacts Test"

inputs:
  name:
    description: Artifact Name
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.inputs.name }}
    - run: ls -R
      shell: /bin/bash
