name: "Push Artifacts"
description: "Push Artifacts Test"
author: "Shane"
branding:
  icon: "image"
  color: "blue"

inputs:
  source:
    description: "Source Directory"
    required: true
  path:
    description: "Backwards Compatibility ONLY! Use: source"
  dest:
    description: "Remote Base Directory"
    default: "/static"
  base:
    description: "Backwards Compatibility ONLY! Use: dest"
  host:
    description: "RSYNC Host"
    required: true
  user:
    description: "RSYNC User"
    required: true
  pass:
    description: "RSYNC Pass"
    required: true
  port:
    description: "RSYNC Port"
    default: "22"
  webhost:
    description: "Remote Web Host Address"
  webhook:
    description: "Discord Webhook"
  comment:
    description: "Add PR Comment"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  url:
    description: "Full Screen Shots URL"

runs:
  using: "docker"
  image: "Dockerfile"
