name: "Push Artifacts"
description: "Push Artifacts Test"
author: "Shane"

inputs:
  name:
    description: Artifact Name
    required: true

runs:
  using: "docker"
  image: "docker://ubuntu:latest"
  args:
    - ${{ inputs.name}}

#  steps:
#    - uses: actions/download-artifact@v3
#      with:
#        name: ${{ github.event.inputs.name }}
#    - run: ls -R
#      shell: /bin/bash
