name: "Push Artifacts"
description: "Push Artifacts Test"
author: "Shane"

inputs:
  path:
    description: "Artifact Path"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
#  args:
#    - ${{ inputs.path}}
