name: "Push Artifacts"
description: "Push Artifacts Test"
author: "Shane"

inputs:
  path:
    description: "Artifact Path"
    required: true
  host:
    description: "SFTP Host"
    required: true
  user:
    description: "SFTP User"
    required: true
  pass:
    description: "SFTP Pass"
    required: true
  port:
    description: "SFTP Port"
    default: "22"
    required: false
  base:
    description: "Remote Base Directory"
    default: "/static"
    required: false
  webhost:
    description: "Remote Web Host Address"
    required: false
  webhook:
    description: "Discord Webhook"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
#  args:
#    - ${{ inputs.path}}
