name: "Push Artifacts"
description: "Push Artifacts Test"
author: "Shane"

inputs:
  path:
    description: "Artifact Path"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path}}

#  steps:
#    - uses: actions/download-artifact@v3
#      with:
#        name: ${{ github.event.inputs.name }}
#    - run: ls -R
#      shell: /bin/bash
