name: "Push Artifacts"
description: "Push Artifacts Test"
author: "Shane"
branding:
  icon: "image"
  color: "blue"

inputs:
  source:
    description: "Source Directory"
    required: true
  dest:
    description: "Remote Base Directory"
    required: false
    default: "/static"
  host:
    description: "RSYNC Host"
    required: true
  user:
    description: "RSYNC User"
    required: true
  pass:
    description: "RSYNC Pass"
    required: true
  port:
    description: "RSYNC Port"
    required: false
    default: "22"
  webhost:
    description: "Remote Web Host Address"
    required: false
  webhook:
    description: "Discord Webhook"
    required: false
  token:
    description: "GitHub Token"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
