name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "ShellCheck"
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: src
          ignore_names: discord.sh
        env:
          SHELLCHECK_OPTS: -e SC2153

      - name: "Prettier"
        if: ${{ always() }}
        run: |
          npx prettier --check .
